version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - FASTAPI_ENV=development
    command: poetry run uvicorn narrativeai.api.api:app --host 0.0.0.0 --port 8000 --reload
